### ISSUE TITLE
Add exposed port to dockerfiles

### ISSUE THREAD

**Issue by tboerger** [promhippie/hetzner_exporter#7]
Currently the dockerfiles are missing the exposed port, that got to be added.

**Comment by albertogviana** [comment]
Hi @tboerger,

Do you have other ports then the one https://github.com/promhippie/hetzner_exporter/blob/master/cmd/hetzner_exporter/main.go#L59?

I would like to work on it!

**Comment by tboerger** [comment]
Fixed via #11
